//
// Created by fightinghawks18 on 12/22/2025.
//

#include "opengl/opengl_loader.h"

// Buffers
PFNGLGENBUFFERSPROC glGenBuffers = CCO_NIL;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = CCO_NIL;
PFNGLBINDBUFFERPROC glBindBuffer = CCO_NIL;
PFNGLBUFFERSUBDATAPROC glBufferSubData = CCO_NIL;
PFNGLBUFFERDATAPROC glBufferData = CCO_NIL;
PFNGLBINDBUFFERBASEPROC glBindBufferBase = CCO_NIL;
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex = CCO_NIL;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding = CCO_NIL;

// Vertex Array Object
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = CCO_NIL;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = CCO_NIL;
PFNGLBINDVERTEXARRAY glBindVertexArray = CCO_NIL;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = CCO_NIL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = CCO_NIL;

// Main
PFNGLENABLEPROC glEnable = CCO_NIL;
PFNGLDISABLEPROC glDisable = CCO_NIL;
PFNGLDEPTHFUNCPROC glDepthFunc = CCO_NIL;
PFNGLVIEWPORTPROC glViewport = CCO_NIL;
PFNGLDEPTHRANGEPROC glDepthRange = CCO_NIL;
PFNGLCLEARPROC glClear = CCO_NIL;
PFNGLCLEARCOLORPROC glClearColor = CCO_NIL;
PFNGLDRAWELEMENTSPROC glDrawElements = CCO_NIL;

// Program
PFNGLCREATEPROGRAMPROC glCreateProgram = CCO_NIL;
PFNGLDELETEPROGRAMPROC glDeleteProgram = CCO_NIL;
PFNGLLINKPROGRAMPROC glLinkProgram = CCO_NIL;
PFNGLGETPROGRAMIVPROC glGetProgramiv = CCO_NIL;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = CCO_NIL;
PFNGLUSEPROGRAMPROC glUseProgram = CCO_NIL;

// Shader
PFNGLATTACHSHADERPROC glAttachShader = CCO_NIL;
PFNGLDETACHSHADERPROC glDetachShader = CCO_NIL;
PFNGLCREATESHADERPROC glCreateShader = CCO_NIL;
PFNGLSHADERSOURCEPROC glShaderSource = CCO_NIL;
PFNGLCOMPILESHADERPROC glCompileShader = CCO_NIL;
PFNGLGETSHADERIVPROC glGetShaderiv = CCO_NIL;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = CCO_NIL;
PFNGLDELETESHADERPROC glDeleteShader = CCO_NIL;